import json
import zipfile
from pathlib import Path
from typing import Any
from core.models import DocumentModel, LensResult


def _clean_title(title: str) -> str:
    return title.replace(" ", "-").replace("/", "-").lower()


def generate_pr_review_markdown(doc_model: DocumentModel) -> str:
    """Generates a rich, collapsible GitHub PR review comment."""
    p_name = doc_model.project_name
    sa = doc_model.static_analysis

    lines = [
        f"## 🤖 CodeLens AI — Architectural & Quality Review for `{p_name}`",
        "",
        "> ⚡ **Automated Analysis Complete:** Multi-lens architectural verification, security scan, and dependency audit.",
        "",
        "### 📊 Quick Summary",
        f"- **Primary Language:** `{sa.primary_language or 'Unknown'}`",
        f"- **Frameworks:** {', '.join(f.name for f in sa.frameworks) or 'None detected'}",
        f"- **Entry Points:** {', '.join(sa.entry_points) or 'None'}",
        f"- **Tests Configured:** `{'✅ Yes' if sa.has_tests else '❌ None detected'}`",
        f"- **CI/CD Pipeline:** `{'✅ ' + (sa.ci_tool or 'Active') if sa.has_ci else '❌ Missing'}`",
        "",
        "---",
        "",
    ]

    for lens in doc_model.lens_results:
        title = lens.title or lens.lens_type.value.replace("_", " ").title()
        lines.append(f"<details><summary><b>🔍 {title}</b></summary>\n")
        lines.append(f"\n{lens.summary}\n")

        if lens.findings:
            lines.append("#### Key Findings:")
            for f in lens.findings[:4]:
                sev_badge = f" `[{f.severity.upper()}]`" if f.severity else ""
                lines.append(f"- **{f.title}**{sev_badge}: {f.description}")
                if f.recommendation:
                    lines.append(f"  - *Fix:* {f.recommendation}")

        if lens.diagrams:
            for diag in lens.diagrams[:1]:
                lines.append(f"\n```{diag.diagram_type}\n{diag.mermaid_code}\n```\n")

        lines.append("\n</details>\n")

    lines.append("\n---\n*Generated by [CodeLens AI](https://github.com/Khevaiya/code-documentation-generator-ai)*")
    return "\n".join(lines)


def create_github_wiki_bundle(doc_model: DocumentModel, out_zip_path: str):
    """Generates a ready-to-commit GitHub Wiki repository zip bundle."""
    zip_path = Path(out_zip_path)
    zip_path.parent.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        # Home.md
        home_lines = [
            f"# {doc_model.project_name} Wiki",
            "",
            "Welcome to the official codebase documentation generated by CodeLens AI.",
            "",
            "## 📚 Navigation",
            "- [[Architecture]]",
            "- [[Security-Audit]]",
            "- [[API-Reference]]",
            "- [[Onboarding]]",
            "- [[Technical-Debt]]",
        ]
        zf.writestr("Home.md", "\n".join(home_lines))

        # _Sidebar.md
        sidebar_lines = [
            "**Documentation**",
            "* [[Home]]",
            "* [[Architecture]]",
            "* [[Security-Audit]]",
            "* [[API-Reference]]",
            "* [[Onboarding]]",
            "* [[Technical-Debt]]",
        ]
        zf.writestr("_Sidebar.md", "\n".join(sidebar_lines))

        # Lens pages
        for lens in doc_model.lens_results:
            page_name = f"{lens.lens_type.value.replace('_', '-').title()}.md"
            content = [
                f"# {lens.title or lens.lens_type.value.title()}",
                "",
                lens.summary,
                "",
            ]
            for f in lens.findings:
                content.append(f"### {f.title}")
                content.append(f.description)
                if f.recommendation:
                    content.append(f"\n> **Recommendation:** {f.recommendation}\n")

            if lens.diagrams:
                for d in lens.diagrams:
                    content.append(f"\n## {d.title}\n```mermaid\n{d.mermaid_code}\n```\n")

            zf.writestr(page_name, "\n".join(content))


def create_docusaurus_bundle(doc_model: DocumentModel, out_zip_path: str):
    """Generates a complete, production-ready Docusaurus documentation website bundle (.zip)."""
    zip_path = Path(out_zip_path)
    zip_path.parent.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        # package.json
        pkg_json = {
            "name": f"{_clean_title(doc_model.project_name)}-docs",
            "version": "1.0.0",
            "private": True,
            "scripts": {
                "docusaurus": "docusaurus",
                "start": "docusaurus start",
                "build": "docusaurus build",
                "serve": "docusaurus serve"
            },
            "dependencies": {
                "@docusaurus/core": "^3.0.0",
                "@docusaurus/preset-classic": "^3.0.0",
                "@mdx-js/react": "^3.0.0",
                "clsx": "^2.0.0",
                "react": "^18.0.0",
                "react-dom": "^18.0.0"
            }
        }
        zf.writestr("package.json", json.dumps(pkg_json, indent=2))

        # docusaurus.config.js
        doc_config = f"""// @ts-check
module.exports = {{
  title: '{doc_model.project_name} Documentation',
  tagline: 'Generated by CodeLens AI',
  url: 'https://your-docusaurus-site.example.com',
  baseUrl: '/',
  onBrokenLinks: 'warn',
  markdown: {{ mermaid: true }},
  themes: ['@docusaurus/theme-mermaid'],
  presets: [
    [
      'classic',
      {{
        docs: {{
          sidebarPath: './sidebars.js',
          routeBasePath: '/',
        }},
        theme: {{
          customCss: './src/css/custom.css',
        }},
      }},
    ],
  ],
}};
"""
        zf.writestr("docusaurus.config.js", doc_config)

        # sidebars.js
        sidebar_config = """module.exports = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};
"""
        zf.writestr("sidebars.js", sidebar_config)
        zf.writestr("src/css/custom.css", ":root { --ifm-color-primary: #6366f1; }")

        # docs/intro.md
        intro_content = f"""---
sidebar_position: 1
---

# {doc_model.project_name} Overview

Welcome to the comprehensive documentation for **{doc_model.project_name}**.

## Summary
{doc_model.executive_summary or 'Multi-lens architecture and security documentation generated by CodeLens AI.'}

## Technical Stack
- **Primary Language:** {doc_model.static_analysis.primary_language or 'Unknown'}
- **Frameworks:** {', '.join(f.name for f in doc_model.static_analysis.frameworks) or 'None detected'}
- **Total Files Analyzed:** {doc_model.static_analysis.has_tests}
"""
        zf.writestr("docs/intro.md", intro_content)

        # Generate each lens doc in docs/
        for idx, lens in enumerate(doc_model.lens_results, start=2):
            slug = _clean_title(lens.lens_type.value)
            title = lens.title or lens.lens_type.value.replace("_", " ").title()
            doc_body = [
                "---",
                f"sidebar_position: {idx}",
                f"title: {title}",
                "---",
                "",
                f"# {title}",
                "",
                lens.summary,
                "",
            ]

            if lens.findings:
                doc_body.append("## Findings & Key Insights")
                for f in lens.findings:
                    doc_body.append(f"### {f.title}")
                    doc_body.append(f.description)
                    if f.recommendation:
                        doc_body.append(f"\n:::tip Recommendation\n{f.recommendation}\n:::\n")

            if lens.diagrams:
                for d in lens.diagrams:
                    doc_body.append(f"## {d.title}\n```mermaid\n{d.mermaid_code}\n```\n")

            zf.writestr(f"docs/{slug}.md", "\n".join(doc_body))
