from core.models import DocumentModel, LensResult, Finding, DiagramSpec, GapItem
from renderers.section_renderer import to_md as _sec_md


def _render_header(doc):
    lines = [
        f"# {doc.project_name} — Codebase Analysis Report", "",
        f"**Generated:** {doc.generated_at.strftime('%B %d, %Y at %H:%M UTC')}  ",
        f"**Input:** {doc.input_type.value}  ",
    ]
    if doc.source_url: lines.append(f"**Source:** {doc.source_url}  ")
    if doc.audience_role: lines.append(f"**Audience:** {doc.audience_role.value.replace('_',' ').title()}  ")
    lines += ["", "---", ""]
    return "\n".join(lines)


def _render_toc(doc):
    lines = ["## Table of Contents", "", "1. [Project Overview](#project-overview)"]
    for i, lr in enumerate(doc.lens_results, 2):
        anchor = lr.title.lower().replace(" ", "-").replace("/", "")
        lines.append(f"{i}. [{lr.title}](#{anchor})")
    return "\n".join(lines) + "\n"


def _render_static_analysis(doc):
    sa = doc.static_analysis
    lines = [
        "## Project Overview", "",
        f"**Primary Language:** {sa.primary_language or 'Unknown'}  ",
        f"**Architecture Pattern:** {sa.architecture_pattern or 'Unknown'}  ",
        f"**Has Tests:** {'Yes' if sa.has_tests else 'No'} ({len(sa.test_files)} test files)  ",
        f"**Has CI/CD:** {'Yes' if sa.has_ci else 'No'}{f' ({sa.ci_tool})' if sa.ci_tool else ''}  ",
        f"**Has Docker:** {'Yes' if sa.has_docker else 'No'}  ",
        f"**README:** {'Present' if sa.readme_exists else 'Missing'}  ", "",
    ]
    if sa.frameworks:
        lines += ["### Frameworks & Libraries", "", "| Framework | Category | Version |", "|-----------|----------|---------|"]
        for fw in sa.frameworks:
            lines.append(f"| {fw.name} | {fw.category} | {fw.version or 'N/A'} |")
        lines.append("")
    if sa.entry_points:
        lines += ["### Entry Points", ""]
        for ep in sa.entry_points: lines.append(f"- `{ep}`")
        lines.append("")
    if sa.api_routes:
        lines += ["### Detected API Routes", ""]
        for route in sa.api_routes[:20]: lines.append(f"- `{route}`")
        lines.append("")
    lines += ["---", ""]
    return "\n".join(lines)


def _render_finding(f):
    icons = {"critical":"🔴","high":"🟠","medium":"🟡","low":"🔵","info":"ℹ️"}
    icon = icons.get(f.severity, "")
    lines = [f"#### {icon} {f.title}", "", f"**Severity:** {f.severity or 'N/A'} | **Category:** {f.category or 'General'}", "", f"{f.description}", ""]
    if f.citations:
        lines += ["**Evidence:**", ""]
        for c in f.citations:
            loc = f"`{c.file_path}`"
            if c.line_start: loc += f" (L{c.line_start}{f'-L{c.line_end}' if c.line_end else ''})"
            lines.append(f"- {loc} [{c.confidence}]")
            if c.snippet: lines += ["  ```", f"  {c.snippet}", "  ```"]
        lines.append("")
    if f.recommendation:
        lines += [f"**Recommendation:** {f.recommendation}", ""]
    return "\n".join(lines)


def _render_lens(lr):
    lines = [f"## {lr.title}", "", lr.summary, ""]
    if lr.diagrams:
        lines += ["### Diagrams", ""]
        for d in lr.diagrams:
            if d.use_svg and d.svg:
                import base64
                b64 = base64.b64encode(d.svg.encode()).decode()
                lines += [f"#### {d.title}", "", f"![{d.title}](data:image/svg+xml;base64,{b64})", ""]
            else:
                lines += [f"#### 📊 {d.title}", "", "```mermaid", d.mermaid_code, "```", ""]
    if lr.findings:
        lines += ["### Findings", ""]
        for f in lr.findings: lines.append(_render_finding(f))
    if lr.raw_sections:
        for sec_name, content in lr.raw_sections.items():
            lines += [f"### {sec_name}", "", _sec_md(content), ""]
    if lr.gaps:
        lines += ["### Gaps & Missing Items", ""]
        for g in lr.gaps:
            icon = {"critical":"🔴","high":"🟠","medium":"🟡","low":"🔵"}.get(g.severity,"")
            lines.append(f"- {icon} **{g.area}:** {g.description}")
            if g.recommendation: lines.append(f"  - *Recommendation:* {g.recommendation}")
        lines.append("")
    lines += ["---", ""]
    return "\n".join(lines)


def render_markdown(doc: DocumentModel, output_path: str) -> str:
    content = "\n".join([
        _render_header(doc), _render_toc(doc), _render_static_analysis(doc),
        *[_render_lens(lr) for lr in doc.lens_results],
        "", "---",
        f"*Report generated by Codebase Analysis Agent on {doc.generated_at.strftime('%Y-%m-%d %H:%M UTC')}*",
    ])
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    return output_path
