from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Image
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF
from io import BytesIO
from core.models import DocumentModel
from renderers.section_renderer import to_md as _sec_md


def _svg_to_image(svg_str: str, max_width: float = 6.5 * inch):
    """Convert SVG string to a ReportLab Drawable scaled to max_width."""
    try:
        drawing = svg2rlg(BytesIO(svg_str.encode("utf-8")))
        if drawing and drawing.width > 0:
            # More conservative scaling to prevent layout errors
            max_page_width = 4.5 * inch  # Reduced from 6.5 to fit frame better
            max_page_height = 7.0 * inch  # Add height limit
            
            scale_x = min(max_page_width / drawing.width, 1.0)
            scale_y = min(max_page_height / drawing.height, 1.0) if drawing.height > 0 else 1.0
            scale = min(scale_x, scale_y)
            
            drawing.width *= scale
            drawing.height *= scale
            drawing.transform = (scale, 0, 0, scale, 0, 0)
            return drawing
    except Exception as e:
        print(f"[pdf_renderer] SVG embed failed: {e}")
    return None


def _get_styles():
    styles = getSampleStyleSheet()
    defs = [
        ("ReportTitle", "Helvetica-Bold", 28, "#1E3A5F", 8, 0, TA_LEFT),
        ("ReportSubtitle", "Helvetica", 14, "#666666", 20, 0, TA_LEFT),
        ("SectionTitle", "Helvetica-Bold", 18, "#1E3A5F", 12, 24, TA_LEFT),
        ("SubsectionTitle", "Helvetica-Bold", 14, "#2E5984", 8, 16, TA_LEFT),
        ("BodyText2", "Helvetica", 10, "#333333", 8, 0, TA_LEFT),
        ("FindingTitle", "Helvetica-Bold", 11, "#333333", 4, 10, TA_LEFT),
        ("SmallGray", "Helvetica", 8, "#999999", 4, 0, TA_LEFT),
        ("Recommendation", "Helvetica-Oblique", 10, "#2E5984", 8, 0, TA_LEFT),
    ]
    for name, font, size, color, after, before, align in defs:
        styles.add(ParagraphStyle(name=name, fontName=font, fontSize=size,
            textColor=HexColor(color), spaceAfter=after, spaceBefore=before, alignment=align, leading=size*1.4))
    return styles


def _severity_color(severity):
    return {"critical":"#CC0000","high":"#FF6600","medium":"#CC8800","low":"#0066CC","info":"#666666"}.get(severity,"#333333")


def _header_footer(canvas, doc_template):
    canvas.saveState()
    canvas.setStrokeColor(HexColor("#1E3A5F"))
    canvas.setLineWidth(0.5)
    canvas.line(72, letter[1]-50, letter[0]-72, letter[1]-50)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(HexColor("#999999"))
    canvas.drawRightString(letter[0]-72, letter[1]-45, "Codebase Analysis Report")
    canvas.line(72, 45, letter[0]-72, 45)
    canvas.drawString(72, 30, "Generated by Codebase Analysis Agent")
    canvas.drawRightString(letter[0]-72, 30, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


def render_pdf(doc: DocumentModel, output_path: str) -> str:
    styles = _get_styles()
    story = []
    pdf_doc = SimpleDocTemplate(output_path, pagesize=letter, leftMargin=72, rightMargin=72, topMargin=72, bottomMargin=72)

    story += [Spacer(1, 1.5*inch), Paragraph(doc.project_name, styles["ReportTitle"]),
              Paragraph("Codebase Analysis Report", styles["ReportSubtitle"]),
              Paragraph(f"Generated: {doc.generated_at.strftime('%B %d, %Y')}", styles["SmallGray"]), PageBreak()]

    sa = doc.static_analysis
    story.append(Paragraph("Project Overview", styles["SectionTitle"]))
    overview_data = [
        ["Primary Language", sa.primary_language or "Unknown"],
        ["Architecture", sa.architecture_pattern or "Unknown"],
        ["Testing", f"{'Yes' if sa.has_tests else 'No'} ({len(sa.test_files)} files)"],
        ["CI/CD", f"{'Yes' if sa.has_ci else 'No'}{f' ({sa.ci_tool})' if sa.ci_tool else ''}"],
        ["Docker", "Yes" if sa.has_docker else "No"],
        ["API Routes", str(len(sa.api_routes))],
    ]
    t = Table(overview_data, colWidths=[2.5*inch, 4*inch])
    t.setStyle(TableStyle([
        ("FONTNAME",(0,0),(0,-1),"Helvetica-Bold"), ("FONTNAME",(1,0),(1,-1),"Helvetica"),
        ("FONTSIZE",(0,0),(-1,-1),10), ("TEXTCOLOR",(0,0),(0,-1),HexColor("#1E3A5F")),
        ("BOTTOMPADDING",(0,0),(-1,-1),8), ("LINEBELOW",(0,0),(-1,-2),0.5,HexColor("#EEEEEE")),
    ]))
    story += [t, Spacer(1, 0.3*inch)]

    if sa.frameworks:
        story.append(Paragraph("Frameworks & Libraries", styles["SubsectionTitle"]))
        fw_data = [["Framework","Category","Version"]] + [[fw.name, fw.category, fw.version or "N/A"] for fw in sa.frameworks]
        ft = Table(fw_data, colWidths=[2.2*inch]*3)
        ft.setStyle(TableStyle([
            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"), ("FONTSIZE",(0,0),(-1,-1),9),
            ("BACKGROUND",(0,0),(-1,0),HexColor("#1E3A5F")), ("TEXTCOLOR",(0,0),(-1,0),HexColor("#FFFFFF")),
            ("BOTTOMPADDING",(0,0),(-1,-1),6), ("GRID",(0,0),(-1,-1),0.5,HexColor("#CCCCCC")),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[HexColor("#FFFFFF"),HexColor("#F5F8FA")]),
        ]))
        story.append(ft)

    for lr in doc.lens_results:
        story += [PageBreak(), Paragraph(lr.title, styles["SectionTitle"]), Paragraph(lr.summary, styles["BodyText2"])]
        if lr.diagrams:
            story.append(Paragraph("Diagrams", styles["SubsectionTitle"]))
            for d in lr.diagrams:
                story.append(Paragraph(f"<b>{d.title}</b> ({d.diagram_type})", styles["FindingTitle"]))
                drawing = _svg_to_image(d.svg) if d.svg else None
                if drawing:
                    story.append(drawing)
                else:
                    # no graph data — skip silently (mermaid can't render in PDF)
                    story.append(Paragraph(f"[Diagram: {d.title}]", styles["SmallGray"]))
                story.append(Spacer(1, 0.1*inch))
        if lr.findings:
            story.append(Paragraph("Findings", styles["SubsectionTitle"]))
            for f in lr.findings:
                color = _severity_color(f.severity)
                story.append(Paragraph(f'<font color="{color}">[{(f.severity or "info").upper()}]</font> {f.title}', styles["FindingTitle"]))
                story.append(Paragraph(f.description, styles["BodyText2"]))
                if f.recommendation:
                    story.append(Paragraph(f"Recommendation: {f.recommendation}", styles["Recommendation"]))
        if lr.gaps:
            story.append(Paragraph("Gaps & Missing Items", styles["SubsectionTitle"]))
            for g in lr.gaps:
                story.append(Paragraph(f"<b>{g.area}:</b> {g.description}", styles["BodyText2"]))
                if g.recommendation:
                    story.append(Paragraph(f"Fix: {g.recommendation}", styles["Recommendation"]))
        if lr.raw_sections:
            story.append(Paragraph("Additional Details", styles["SubsectionTitle"]))
            for sec_name, sec_content in lr.raw_sections.items():
                story.append(Paragraph(sec_name, styles["SubsectionTitle"]))
                rendered = _sec_md(sec_content)
                for line in rendered.splitlines():
                    if line.strip():
                        story.append(Paragraph(line.replace("**", ""), styles["BodyText2"]))

    pdf_doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return output_path
